const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const state={products:[],filtered:[],details:{},cart:JSON.parse(localStorage.getItem('nc_cart')||'[]'),wishlist:JSON.parse(localStorage.getItem('nc_wishlist')||'[]'),category:'all',sort:'featured',query:'',page:0,total:0,pageSize:12,categories:[],loading:false,error:'',requestId:0,grid:true,coupon:null,customer:null,csrf:'',currency:'USD',storeConfig:{shipping:{standard:5.99,freeThreshold:75,express:12.99},taxRate:0}};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:state.currency}).format(Number(n||0));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cartLineProduct=(i)=>{const d=state.details[i.id];const v=i.variantId&&d?.variants?.find(x=>x.id===i.variantId);return {p:d||state.products.find(x=>x.id===i.id),v};};
const linePrice=i=>{const {p,v}=cartLineProduct(i);return Number(v?.price??p?.price??0)};
async function getCsrf(){if(state.csrf)return state.csrf;try{const r=await fetch('/api/auth/csrf');const j=await r.json();if(r.ok){state.csrf=j.csrfToken;return state.csrf}}catch{}return ''}
const save=()=>{localStorage.setItem('nc_cart',JSON.stringify(state.cart));localStorage.setItem('nc_wishlist',JSON.stringify(state.wishlist));};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2400)}
async function load(){try{
 const [cfg,categories]=await Promise.all([fetch('/api/store-config'),fetch('/api/categories')]);
 if(!cfg.ok||!categories.ok)throw new Error('Store configuration is unavailable.');
 const c=await cfg.json();state.categories=(await categories.json()).categories||[];
 state.storeConfig={...state.storeConfig,...c,shipping:{...state.storeConfig.shipping,...(c.shipping||{})}};state.currency=c.currency||'USD';
 const raw=localStorage.getItem('novacart_user');if(raw){try{state.customer=JSON.parse(raw)}catch{}}
 await Promise.all([...new Set([...state.cart.map(x=>x.id),...state.wishlist])].map(loadDetail));
 const initialParams=new URLSearchParams(location.search);if(initialParams.get('sort')==='new'){state.sort='new';$('#sortFilter').value='new';}if(initialParams.get('q')){state.query=initialParams.get('q');$('#searchInput').value=state.query;}if(initialParams.get('cat'))state.category=initialParams.get('cat').toLowerCase();buildCategories();await apply();renderDeals();renderCart();renderWishlist();updateCounts();
 const params=new URLSearchParams(location.search);if(params.get('checkout')==='1')setTimeout(openCheckout,250);else if(params.get('drawer')==='cart')openDrawer();else if(params.get('drawer')==='wishlist')openWishlist();
 }catch(e){toast(e.message||'Could not load the store.');}}
function cacheProducts(products){const cached=new Map(state.products.map(p=>[p.id,p]));products.forEach(p=>cached.set(p.id,p));state.products=[...cached.values()];}
async function loadDetail(id){const r=await fetch('/api/products/'+encodeURIComponent(id));if(r.ok){const p=(await r.json()).product;state.details[p.id]=p;cacheProducts([p]);}}

function buildCategories(){const cats=['All',...state.categories];$('#categoryPills').innerHTML=cats.map(c=>`<button class="cat-pill ${c.toLowerCase()===state.category?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');$$('.cat-pill').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat.toLowerCase();apply()});}
async function apply(append=false){
 clearTimeout(state.searchTimer);
 if(append&&(state.loading||state.filtered.length>=state.total))return;
 state.controller?.abort();const controller=state.controller=new AbortController();
 const requestId=++state.requestId,page=append?state.page+1:1;
 if(!append){state.page=0;state.filtered=[];state.total=0;}
 state.loading=true;state.error='';renderProducts();
 const params=new URLSearchParams({q:state.query.trim(),cat:state.category,sort:state.sort,page:String(page),limit:String(state.pageSize)});
 try{
  const r=await fetch('/api/products?'+params,{signal:controller.signal}),j=await r.json();
  if(!r.ok)throw new Error(j.error||'Products could not be loaded.');
  if(requestId!==state.requestId)return;
  const products=j.products||[];cacheProducts(products);
  state.filtered=append?[...new Map([...state.filtered,...products].map(p=>[p.id,p])).values()]:products;
  state.page=j.pagination.page;state.total=j.pagination.total;
 }catch(e){if(requestId===state.requestId&&e.name!=='AbortError'){state.error=e.message||'Products could not be loaded.';toast(state.error);}}
 finally{if(requestId===state.requestId){state.loading=false;renderProducts();$$('.cat-pill').forEach(b=>b.classList.toggle('active',b.dataset.cat.toLowerCase()===state.category));}}
}
function queueSearch(){
 state.query=$('#searchInput').value;clearTimeout(state.searchTimer);state.controller?.abort();state.requestId++;
 state.page=0;state.filtered=[];state.total=0;state.loading=true;state.error='';renderProducts();
 state.searchTimer=setTimeout(()=>apply(),250);
}
function stars(r){return `<span class="stars" aria-hidden="true">★</span> <span class="rating-num">${Number(r||0).toFixed(1)}</span>`}
const heartIcon='<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/></svg>';
function productCard(p){
 const fav=state.wishlist.includes(p.id),pct=Number(p.oldPrice)>Number(p.price)?Math.round((1-p.price/p.oldPrice)*100):0,url='/product.html?id='+encodeURIComponent(p.id);
 return `<article class="product-card" data-id="${esc(p.id)}"><button class="fav ${fav?'active':''}" data-fav="${esc(p.id)}" aria-label="${fav?'Remove from':'Save to'} favourites: ${esc(p.title)}" aria-pressed="${fav}">${heartIcon}</button><a class="product-media" href="${url}" aria-label="View ${esc(p.title)}"><img src="${esc(p.image)}" alt="${esc(p.title)}" loading="lazy" width="400" height="400">${p.badge||pct?`<span class="badge">${esc(p.badge||`${pct}% OFF`)}</span>`:''}${Number(p.stock)===0?'<span class="stock-badge">Out of stock</span>':''}<span class="quick-view">Discover this find ↗</span></a><div class="product-info"><span class="product-cat">${esc(p.cat)}</span><h3><a href="${url}">${esc(p.title)}</a></h3>${Number(p.reviews)>0?`<div class="rating" aria-label="Rated ${Number(p.rating||0).toFixed(1)} out of 5, ${Number(p.reviews||0)} reviews">${stars(p.rating)} <span>(${Number(p.reviews||0).toLocaleString()})</span></div>`:`<div class="rating no-reviews">No reviews yet</div>`}<div class="price-row"><strong>${money(p.price)}</strong>${pct?`<del>${money(p.oldPrice)}</del>`:''}<button class="add-btn" data-add="${esc(p.id)}" aria-label="Add ${esc(p.title)} to bag" ${Number(p.stock)===0?'disabled':''}>+</button></div></div></article>`;
}
function renderProducts(){
 const grid=$('#products');grid.classList.toggle('list-view',!state.grid);
 grid.innerHTML=state.filtered.map(productCard).join('')||(state.loading?Array.from({length:4},()=>'<div class="skeleton" aria-hidden="true"></div>').join(''):`<div class="empty-state"><h3>${state.error?'A little pause in browsing.':'Nothing here just yet.'}</h3><p>${state.error?'Please try again to load your finds.':'Try another search or explore a different category.'}</p></div>`);
 const more=$('#loadMore');more.style.display=state.loading||state.error||state.filtered.length<state.total?'block':'none';more.disabled=state.loading;more.textContent=state.loading?'Finding more…':state.error?'Try again':'Discover more ↓';
 grid.setAttribute('aria-busy',String(state.loading));
 const count=$('#catalogCount');if(count)count.textContent=state.loading?'Finding your favourites…':`${state.filtered.length} of ${state.total} finds`;
 $('#viewGrid').setAttribute('aria-pressed',String(state.grid));$('#viewList').setAttribute('aria-pressed',String(!state.grid));
 $$('#products [data-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();addCart(b.dataset.add,1,null,b)});
 $$('#products [data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.fav)});
 $$('.category-nav [data-cat]').forEach(a=>a.classList.toggle('active',a.dataset.cat.toLowerCase()===state.category));
}
function renderDeals(){
 const ds=[...state.products].filter(p=>Number(p.oldPrice)>Number(p.price)).sort((a,b)=>(b.oldPrice-b.price)-(a.oldPrice-a.price)).slice(0,4);
 $('#deals').hidden=!ds.length;
 $('#dealGrid').innerHTML=ds.map(p=>`<article class="deal-card"><div><span class="kicker">${Math.round((1-p.price/p.oldPrice)*100)}% LESS, MORE TO LOVE</span><h3><a href="/product.html?id=${encodeURIComponent(p.id)}">${esc(p.title)}</a></h3><div class="deal-price"><strong>${money(p.price)}</strong><del>${money(p.oldPrice)}</del></div><button class="add-btn large" data-add="${esc(p.id)}" aria-label="Add ${esc(p.title)} to bag">Add to bag +</button></div><img src="${esc(p.image)}" alt="${esc(p.title)}" loading="lazy"></article>`).join('');
 $$('#dealGrid [data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add,1,null,b));
}
function renderAll(){apply();renderDeals();renderCart();renderWishlist()}
function addCart(id,qty=1,variantId=null,source=null){const previous=state.cart.reduce((s,i)=>s+i.qty,0);const key=variantId||id;const item=state.cart.find(x=>(x.variantId||x.id)===key);if(item)item.qty=Math.min(20,item.qty+qty);else state.cart.push({id,variantId,qty:Math.min(20,qty)});save();updateCounts();renderCart();toast('A good find. Added to your bag.');if(state.cart.reduce((s,i)=>s+i.qty,0)>previous)document.dispatchEvent(new CustomEvent('novacart:cart-added',{detail:{source}}))}
function removeCart(key){state.cart=state.cart.filter(x=>(x.variantId||x.id)!==key);save();updateCounts();renderCart()}
function changeQty(key,d){const x=state.cart.find(i=>(i.variantId||i.id)===key);if(!x)return;x.qty+=d;if(x.qty<1)removeCart(key);else{x.qty=Math.min(20,x.qty);save();renderCart();updateCounts()}}
function cartTotal(){return state.cart.reduce((s,i)=>s+linePrice(i)*i.qty,0)}
function renderCart(){const box=$('#cartItems');if(!state.cart.length){box.innerHTML=`<div class="empty-cart"><div aria-hidden="true">✳</div><h3>Your bag is waiting</h3><p>Discover something you’ll love.</p><a href="#shop" class="primary-btn" onclick="closeDrawer()">Start shopping →</a></div>`}else box.innerHTML=state.cart.map(i=>{const {p,v}=cartLineProduct(i);if(!p)return '';const price=linePrice(i);const label=v?.title?`${p.title} · ${v.title}`:p.title;const key=v?.id||p.id;return `<div class="cart-line"><img src="${esc(v?.image||p.image)}" alt="${esc(label)}" loading="lazy"><div><span>${esc(p.cat)}</span><h4>${esc(label)}</h4><strong>${money(price)}</strong><div class="qty"><button data-q="${esc(key)}" data-d="-1" aria-label="Decrease quantity">−</button><b>${i.qty}</b><button data-q="${esc(key)}" data-d="1" aria-label="Increase quantity">+</button><button class="remove" data-r="${esc(key)}">Remove</button></div></div></div>`}).join('');$('#subtotal').textContent=money(cartTotal());$$('#cartItems [data-q]').forEach(b=>b.onclick=()=>changeQty(b.dataset.q,Number(b.dataset.d)));$$('#cartItems [data-r]').forEach(b=>b.onclick=()=>removeCart(b.dataset.r))}
function updateCounts(){$('#cartCount').textContent=state.cart.reduce((s,i)=>s+i.qty,0);$('#wishlistCount').textContent=state.wishlist.length}
async function toggleFav(id){const i=state.wishlist.indexOf(id);const adding=i===-1;if(adding)state.wishlist.push(id);else state.wishlist.splice(i,1);save();updateCounts();renderProducts();renderWishlist();document.dispatchEvent(new CustomEvent('novacart:wishlist-changed',{detail:{added:adding,source:[...document.querySelectorAll('[data-fav]')].find(b=>b.dataset.fav===id)}}));try{const me=await fetch('/api/auth/me');if(me.ok){const csrf=await getCsrf();await fetch(`/api/wishlist/${encodeURIComponent(id)}`,{method:adding?'PUT':'DELETE',headers:{'x-csrf-token':csrf}})}}catch{}}
function renderWishlist(){const box=$('#wishlistItems');if(!state.wishlist.length){box.innerHTML='<div class="empty-cart"><div>♡</div><h3>Nothing saved yet</h3><p>Tap the heart on anything you like.</p></div>';return}box.innerHTML=state.wishlist.map(id=>{const p=state.details[id]||state.products.find(x=>x.id===id);return p?`<div class="cart-line"><img src="${esc(p.image)}" alt="${esc(p.title)}"><div><span>${esc(p.cat)}</span><h4>${esc(p.title)}</h4><strong>${money(p.price)}</strong><button class="mini-action" data-add="${esc(p.id)}">Add to cart</button></div></div>`:''}).join('');$$('#wishlistItems [data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add,1,null,b))}
function openDrawer(){hideAllOverlays();$('#cartDrawer').classList.add('open');$('#backdrop').classList.add('show')};function openWishlist(){hideAllOverlays();$('#wishlistDrawer').classList.add('open');$('#backdrop').classList.add('show')};function closeDrawer(){hideAllOverlays()};function hideAllOverlays(){$$('.drawer').forEach(x=>x.classList.remove('open'));$('#backdrop').classList.remove('show');$$('.modal').forEach(x=>x.classList.remove('show'))}window.closeDrawer=closeDrawer;
function openProduct(id){if(!id)return;location.href='/product.html?id='+encodeURIComponent(id)}
async function loadCustomer(){try{const r=await fetch('/api/auth/me');if(!r.ok)return null;const j=await r.json();state.customer=j.user;localStorage.setItem('novacart_user',JSON.stringify(j.user));const c=await fetch('/api/customer');if(c.ok){const cj=await c.json();state.customer={...state.customer,...cj.customer}}const cr=await fetch('/api/auth/csrf');if(cr.ok){const cj=await cr.json();state.csrf=cj.csrfToken}return state.customer}catch{return null}}
function fillAddress(a){$('#addressName').value=a?.fullName||state.customer?.name||'';$('#addressLine1').value=a?.line1||'';$('#addressLine2').value=a?.line2||'';$('#addressCity').value=a?.city||'';$('#addressPostal').value=a?.postalCode||'';$('#addressCountry').value=a?.country||'Sri Lanka';}
function renderSavedAddresses(){const box=$('#savedAddresses');const list=state.customer?.addresses||[];box.innerHTML=list.length?list.map((a,i)=>`<button type="button" class="saved-address ${i===0?'selected':''}" data-addr="${i}"><b>${esc(a.label||'Address '+(i+1))}</b><span>${esc(a.fullName)} · ${esc(a.line1)}, ${esc(a.city)} ${esc(a.postalCode)}</span></button>`).join(''):'<div class="no-saved-address">No saved addresses yet. Add one below and save it for next time.</div>';$$('.saved-address').forEach(b=>b.onclick=()=>{$$('.saved-address').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');fillAddress(list[Number(b.dataset.addr)])})}
function checkoutEstimate(){const subtotal=cartTotal();const discount=state.coupon?Math.min(subtotal,Number(state.couponDiscount||0)):0;const delivery=document.querySelector('input[name="delivery"]:checked')?.value||'standard';const shipping=delivery==='express'?Number(state.storeConfig.shipping?.express??12.99):(subtotal-discount>=Number(state.storeConfig.shipping?.freeThreshold??75)?0:Number(state.storeConfig.shipping?.standard??5.99));const tax=Math.round(Math.max(0,subtotal-discount)*Number(state.storeConfig.taxRate||0)*100)/100;const total=Math.max(0,subtotal-discount+shipping+tax);const standardLabel=$('#standardShippingLabel'),expressLabel=$('#expressShippingLabel');if(standardLabel)standardLabel.textContent=`${money(state.storeConfig.shipping.standard)} · free over ${money(state.storeConfig.shipping.freeThreshold)}`;if(expressLabel)expressLabel.textContent=money(state.storeConfig.shipping.express);$('#reviewSubtotal').textContent=money(subtotal);$('#reviewDiscount').textContent='−'+money(discount);$('#reviewShipping').textContent=shipping?money(shipping):'FREE';$('#reviewTax').textContent=money(tax);$('#reviewTotal').textContent=money(total);$('#reviewItemCount').textContent=state.cart.reduce((s,i)=>s+i.qty,0)+' item'+(state.cart.reduce((s,i)=>s+i.qty,0)===1?'':'s');return {subtotal,discount,shipping,tax,total}}
async function openCheckout(){if(!state.cart.length){toast('Your bag is waiting');return}hideAllOverlays();await loadCustomer();$('#emailInput').value=state.customer?.email||'';$('#phoneInput').value=state.customer?.phone||'';const saved=state.customer?.addresses?.[0];fillAddress(saved);renderSavedAddresses();$('#checkoutSummary').innerHTML=state.cart.map(i=>{const {p,v}=cartLineProduct(i);if(!p)return '';const title=v?.title?`${p.title} · ${v.title}`:p.title;return `<div class="checkout-row"><span><b>${i.qty}×</b> ${esc(title)}</span><strong>${money(linePrice(i)*i.qty)}</strong></div>`}).join('');state.coupon=null;state.couponDiscount=0;$('#couponInput').value='';$('#couponNote').innerHTML='Use an active store coupon for eligible orders.';checkoutEstimate();$('#checkoutModal').classList.add('show')}
async function saveCurrentAddress(){const a={id:'a-'+Date.now(),label:'Home',fullName:$('#addressName').value.trim(),line1:$('#addressLine1').value.trim(),line2:$('#addressLine2').value.trim(),city:$('#addressCity').value.trim(),postalCode:$('#addressPostal').value.trim(),country:$('#addressCountry').value};if(!a.fullName||!a.line1||!a.city||!a.postalCode){toast('Complete the address before saving');return}if(!state.customer){toast('Sign in first to save an address');return}const existing=(state.customer?.addresses||[]).filter(x=>!(x.line1===a.line1&&x.postalCode===a.postalCode));existing.unshift(a);if(!state.csrf){const cr=await fetch('/api/auth/csrf');if(cr.ok){state.csrf=(await cr.json()).csrfToken}}const r=await fetch('/api/customer',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':state.csrf},body:JSON.stringify({name:a.fullName,phone:$('#phoneInput').value.trim(),addresses:existing})});const j=await r.json();if(r.ok){const fresh=await fetch('/api/customer');state.customer=(await fresh.json()).customer;renderSavedAddresses();toast('Address saved securely')}else toast(j.error||'Could not save address')}
async function checkout(){const email=$('#emailInput').value.trim();if(!email||!email.includes('@'))return toast('Enter a valid email');const address={fullName:$('#addressName').value.trim(),line1:$('#addressLine1').value.trim(),line2:$('#addressLine2').value.trim(),city:$('#addressCity').value.trim(),postalCode:$('#addressPostal').value.trim(),country:$('#addressCountry').value};for(const [k,v] of Object.entries({fullName:address.fullName,line1:address.line1,city:address.city,postalCode:address.postalCode,country:address.country})){if(!v)return toast('Complete your shipping address')}const payment=document.querySelector('input[name="payment"]:checked')?.value||'stripe';const delivery=document.querySelector('input[name="delivery"]:checked')?.value||'standard';const body={email,phone:$('#phoneInput').value.trim(),customerName:address.fullName,items:state.cart,shippingAddress:address,paymentMethod:payment,delivery,coupon:state.coupon};const idem=(globalThis.crypto?.randomUUID?globalThis.crypto.randomUUID():`${Date.now()}-${Math.random()}`).replace(/-/g,'').slice(0,32);const btn=$('#payBtn');btn.disabled=true;btn.textContent=payment==='cod'?'Placing cash-on-delivery order…':'Opening secure payment…';try{const r=await fetch('/api/checkout',{method:'POST',headers:{'content-type':'application/json','Idempotency-Key':idem,...(state.csrf?{'x-csrf-token':state.csrf}:{})},body:JSON.stringify(body)});const j=await r.json();if(j.mode==='stripe'&&j.url){location.href=j.url;return}if(j.orderId){state.cart=[];save();updateCounts();renderCart();hideAllOverlays();toast(`Order ${j.orderId} created`);setTimeout(()=>location.href='/orders.html',700)}else toast(j.error||'Checkout failed')}catch{toast('Checkout failed. Please try again.')}finally{btn.disabled=false;btn.textContent='Place order securely →'}}
async function applyCoupon(){const code=$('#couponInput').value.trim().toUpperCase();if(!code){state.coupon=null;state.couponDiscount=0;$('#couponNote').textContent='Enter an active store coupon for an eligible order.';return checkoutEstimate()}try{const r=await fetch('/api/coupons/validate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,subtotal:cartTotal()})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Invalid coupon');state.coupon=code;state.couponDiscount=Number(j.discount||0);$('#couponNote').innerHTML=`<b>✓ ${esc(code)} applied</b> — you saved ${money(j.discount)}.`;toast('Coupon applied')}catch(e){state.coupon=null;state.couponDiscount=0;$('#couponNote').textContent=e.message;toast(e.message)}checkoutEstimate()}
function search(){state.query=$('#searchInput').value;apply();document.querySelector('#shop').scrollIntoView({behavior:document.documentElement.classList.contains('nc-motion-off')?'instant':'smooth'});}
$('#searchInput').addEventListener('input',queueSearch);$('#searchInput').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();search();}});$('#searchButton').onclick=search;$('#sortFilter').onchange=e=>{state.sort=e.target.value;apply()};$('#loadMore').onclick=()=>apply(state.page>0);$('#viewGrid').onclick=()=>{state.grid=true;$('#viewGrid').classList.add('active');$('#viewList').classList.remove('active');renderProducts()};$('#viewList').onclick=()=>{state.grid=false;$('#viewList').classList.add('active');$('#viewGrid').classList.remove('active');renderProducts()};$('#cartOpen').onclick=openDrawer;$('#wishlistOpen').onclick=openWishlist;$('#closeCart').onclick=closeDrawer;$('#closeWishlist').onclick=closeDrawer;$('#backdrop').onclick=closeDrawer;$('#productClose').onclick=closeDrawer;$('#checkoutClose').onclick=closeDrawer;$('#checkoutBtn').onclick=openCheckout;$('#payBtn').onclick=checkout;$('#saveAddressBtn').onclick=saveCurrentAddress;$('#couponBtn').onclick=applyCoupon;$$('input[name="delivery"]').forEach(x=>x.onchange=checkoutEstimate);$$('input[name="payment"]').forEach(x=>x.onchange=()=>$$('.payment-card').forEach(c=>c.classList.toggle('active',c.querySelector('input').checked)));$('#newsletterForm').onsubmit=async e=>{e.preventDefault();const email=$('#newsletterEmail').value.trim();try{const r=await fetch('/api/newsletter',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not subscribe.');toast('Welcome to NovaCart ✦');e.target.reset()}catch(err){toast(err.message)}};$('#mobileMenuBtn').onclick=()=>{const open=$('#mobileNav').classList.toggle('open');$('#mobileMenuBtn').setAttribute('aria-expanded',String(open));};$('#searchCategory').onclick=()=>{state.category='all';apply();$('#shop').scrollIntoView({behavior:document.documentElement.classList.contains('nc-motion-off')?'instant':'smooth'});};$$('a[data-cat]').forEach(a=>a.onclick=e=>{if(a.dataset.cat==='new'){state.sort='new';state.query='';state.category='all';$('#searchInput').value='';$('#sortFilter').value='new'}else state.category=a.dataset.cat.toLowerCase();$('#mobileNav').classList.remove('open');$('#mobileMenuBtn').setAttribute('aria-expanded','false');document.querySelector('#shop').scrollIntoView({behavior:document.documentElement.classList.contains('nc-motion-off')?'instant':'smooth'});apply()});load();

// V9 customer greeting: surface the signed-in customer without changing checkout behavior.
(async()=>{try{const r=await fetch('/api/auth/me');if(!r.ok)return;const j=await r.json();const name=j.user?.name?.split(' ')[0];if(!name)return;const nav=document.querySelector('.header-actions');if(nav&&!document.querySelector('.customer-greeting')){const g=document.createElement('div');g.className='customer-greeting';const dot=document.createElement('span');dot.className='dot';const text=document.createElement('span');text.textContent='Hi, '+name;g.append(dot,text);nav.prepend(g)}}catch{}})();
