(()=>{
  'use strict';
  const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let csrf='',selection=null,preview=null,cancelId=null;
  async function api(path,body){const r=await fetch(path,{...(body?{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify(body)}:{})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed.');return j;}
  async function refresh(){
    const data=await api('/api/admin/suppliers');
    $('#supplierProviders').innerHTML=Object.entries(data.providers).map(([name,p])=>`<div class="provider-status"><strong>${name==='amazon'?'Amazon MCF':'AliExpress'}</strong><p>${p.enabled&&p.configured?'Product sync configured':'Needs server configuration'} · ${p.forwarding&&p.enabled&&p.configured?'Forwarding enabled':'Forwarding off'}</p><small>${esc(p.mode)}</small></div>`).join('');
    $('#supplierAutomation').textContent=(data.automation?.enabled?'Scheduled sync enabled: shipments every 5 minutes; stock every 6 hours.':'Scheduled sync is off. Set SUPPLIER_AUTO_SYNC=true on the server and restart to enable it.')+' Orders require review before submission. Supplier payments are completed in the provider account.';
    $('#supplierProducts').innerHTML=data.products.length?`<table><thead><tr><th>Product</th><th>Source</th><th>Stock</th><th>Retail</th><th>Last sync</th><th></th></tr></thead><tbody>${data.products.map(p=>`<tr><td>${esc(p.title)}<small>${p.active?'Published':'Draft — publish in Product studio'}</small></td><td>${esc(p.provider)} · ${esc(p.country)}<small>${esc(p.external_id)} / ${esc(p.external_sku)}</small></td><td>${p.stock}<small>Supplier: ${p.supplier_stock}</small></td><td>${esc(p.currency)} ${Number(p.price).toFixed(2)}</td><td>${new Date(p.last_synced_at).toLocaleString()}</td><td><button class="save" data-sync="${esc(p.id)}">Sync</button></td></tr>`).join('')}</tbody></table>`:'<p class="integration-help">Your imported products will appear here.</p>';
    $('#supplierOrders').innerHTML=data.orders.length?`<table><thead><tr><th>Store order</th><th>Supplier</th><th>Fulfillment / payment</th><th>Tracking</th><th>Actions</th></tr></thead><tbody>${data.orders.map(o=>`<tr><td>${esc(o.orderId)}<small>${esc(o.externalIds?.join(', ')||o.reference)}</small></td><td>${esc(o.provider)}<small>Submission: ${esc(o.status)}</small></td><td>${esc(o.fulfillmentStatus||'pending')}<small>Supplier payment: ${esc(o.supplierPaymentStatus||'unknown')}</small><small>Cancellation: ${esc(o.cancelStatus||'none')}</small><small>${esc(o.message)}</small></td><td>${(o.packages||[]).map(p=>`<small>${esc(p.courier)} · ${esc(p.trackingNumber)} · ${esc(p.status)}</small>`).join('')||'Awaiting tracking'}<small>${o.lastSyncAt?'Checked '+new Date(o.lastSyncAt).toLocaleString():'Not checked'}</small><small>${esc(o.syncError||'')}</small></td><td>${['unknown','submitting','submitted'].includes(o.status)?`<button class="save" data-track-sync="${esc(o.id)}">Sync status</button>`:''}${o.status==='submitted'?`<button class="save" data-cancel-supplier="${esc(o.id)}">Cancellation</button>`:''}${o.provider==='aliexpress'?'<a class="save" href="https://www.aliexpress.com/" target="_blank" rel="noopener noreferrer">Open AliExpress</a>':''}${['unknown','submitting'].includes(o.status)?`<button class="save" data-resolve="${esc(o.id)}">Record verified outcome</button>`:''}</td></tr>`).join('')}</tbody></table>`:'<p class="integration-help">No supplier shipment has been prepared yet.</p>';
    document.querySelectorAll('[data-track-sync]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('/api/admin/supplier-orders/'+b.dataset.trackSync+'/sync',{});await refresh();$('#integrationStatus').textContent='Provider status and customer tracking refreshed.';}catch(e){$('#integrationStatus').textContent=e.message;b.disabled=false;}});
    document.querySelectorAll('[data-cancel-supplier]').forEach(b=>b.onclick=()=>{const o=data.orders.find(o=>o.id===b.dataset.cancelSupplier);cancelId=o.id;$('#supplierCancelPanel').hidden=false;$('#supplierCancelReference').textContent=o.orderId+' · '+o.provider+' · '+(o.externalIds?.join(', ')||o.reference);$('#confirmSupplierCancel').disabled=o.cancelStatus!=='none';$('#supplierCancelPanel').scrollIntoView({behavior:document.documentElement.classList.contains('nc-motion-off')?'instant':'smooth'});});

    document.querySelectorAll('[data-sync]').forEach(button=>button.onclick=async()=>{button.disabled=true;$('#integrationStatus').textContent='Syncing supplier stock…';try{await api('/api/admin/supplier-products/'+button.dataset.sync+'/sync',{});await refresh();$('#integrationStatus').textContent='Stock and product details updated. Your retail price was preserved.';}catch(e){$('#integrationStatus').textContent=e.message;button.disabled=false;}});
    document.querySelectorAll('[data-resolve]').forEach(button=>button.onclick=()=>{const row=data.orders.find(o=>o.id===button.dataset.resolve);$('#resolveShipmentId').value=row.id;$('#resolutionReference').textContent=row.provider+' · '+row.orderId+' · '+row.reference;$('#supplierResolution').hidden=false;$('#supplierResolution').scrollIntoView({behavior:document.documentElement.classList.contains('nc-motion-off')?'instant':'smooth'});$('#resolutionEvidence').focus();});
    document.querySelectorAll('[data-reconcile]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await api('/api/admin/supplier-orders/'+button.dataset.reconcile+'/reconcile',{});await refresh();$('#integrationStatus').textContent='Provider status verified.';}catch(e){$('#integrationStatus').textContent=e.message;button.disabled=false;}});
  }
  $('#supplierCheckForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget)),b=e.currentTarget.querySelector('button');b.disabled=true;try{const r=await api('/api/admin/suppliers/'+v.provider+'/check',v);$('#supplierCheckStatus').textContent=r.message+' Product: '+r.product.title;}catch(err){$('#supplierCheckStatus').textContent=err.message;}finally{b.disabled=false;}};
  $('#confirmSupplierCancel').onclick=async()=>{if(!cancelId)return;const b=$('#confirmSupplierCancel');b.disabled=true;try{const r=await api('/api/admin/supplier-orders/'+cancelId+'/cancel',{confirm:true});$('#supplierCancelStatus').textContent=r.message||'Cancellation already recorded. Sync provider status.';}catch(e){$('#supplierCancelStatus').textContent=e.message;}finally{await refresh();}};
  $('#supplierCancelReview').onsubmit=async e=>{e.preventDefault();if(!cancelId)return;const f=e.currentTarget,b=f.querySelector('button');b.disabled=true;try{const r=await api('/api/admin/supplier-orders/'+cancelId+'/cancel-review',{outcome:f.elements.outcome.value,evidence:f.elements.evidence.value,providerChecked:f.elements.providerChecked.checked});$('#supplierCancelStatus').textContent=r.message;await refresh();}catch(err){$('#supplierCancelStatus').textContent=err.message;}finally{b.disabled=false;}};
  $('#supplierImportForm').oninput=()=>{selection=null;$('#supplierProductPreview').hidden=true;};
  $('#supplierImportForm').onsubmit=async event=>{
    event.preventDefault();const f=event.currentTarget,b=f.querySelector('[type=submit]');b.disabled=true;$('#importStatus').textContent='Getting product and stock details…';selection=null;
    const value=Object.fromEntries(new FormData(f));
    try{const {product:p}=await api('/api/admin/suppliers/'+value.provider+'/product',value);selection=value;$('#supplierProductPreview').hidden=false;$('#supplierProductSummary').innerHTML=`<img src="${esc(p.image)}" alt=""><h3>${esc(p.title)}</h3><p>${p.stock} units reported · ${esc(p.country)}${p.cost!==null?' · Supplier item cost '+esc(p.currency)+' '+Number(p.cost).toFixed(2):''}</p><p>Review supplier delivery charges and product rights before publishing. Your retail price is set independently.</p>`;$('#importStatus').textContent='Product verified. Choose your retail price below.';}catch(e){$('#importStatus').textContent=e.message;}finally{b.disabled=false;}
  };
  $('#confirmImport').onclick=async()=>{
    if(!selection)return;const b=$('#confirmImport');b.disabled=true;
    try{const result=await api('/api/admin/suppliers/'+selection.provider+'/import',{...selection,retailPrice:$('#supplierRetailPrice').value,category:$('#supplierCategory').value,publish:$('#supplierPublish').checked});$('#importStatus').textContent='Imported '+result.productId+'. '+(result.retailPricePreserved?'Existing retail price preserved.':'Manage it in Product studio.');selection=null;$('#supplierProductPreview').hidden=true;await refresh();}catch(e){$('#importStatus').textContent=e.message;}finally{b.disabled=false;}
  };
  $('#supplierOrderForm').oninput=()=>{preview=null;$('#supplierOrderPreview').hidden=true;};
  $('#supplierOrderForm').onsubmit=async event=>{
    event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget)),b=event.currentTarget.querySelector('[type=submit]');b.disabled=true;$('#forwardStatus').textContent='Checking the paid order…';preview=null;
    try{preview=await api('/api/admin/suppliers/'+values.provider+'/orders/'+encodeURIComponent(values.orderId)+'/preview',{});$('#supplierOrderPreview').hidden=false;const a=preview.address;$('#supplierOrderSummary').innerHTML=`<h3>Review this shipment</h3><ul>${preview.items.map(i=>`<li>${esc(i.title)} × ${i.qty}<br><small>SKU ${esc(i.sku)}</small></li>`).join('')}</ul><pre>${esc([a.fullName,a.line1,a.line2,a.city+' '+(a.state||'')+' '+a.postalCode,a.country,preview.phone].filter(Boolean).join('\n'))}</pre><p>${esc(preview.message)}</p>`;$('#forwardStatus').textContent='Preview ready for 10 minutes.';}catch(e){$('#forwardStatus').textContent=e.message;}finally{b.disabled=false;}
  };
  $('#confirmForward').onclick=async()=>{
    if(!preview)return;const b=$('#confirmForward');b.disabled=true;
    try{const result=await api('/api/admin/suppliers/'+preview.provider+'/orders/'+encodeURIComponent(preview.orderId)+'/forward',{previewId:preview.previewId,confirm:true});$('#forwardStatus').textContent=result.message;preview=null;$('#supplierOrderPreview').hidden=true;}catch(e){$('#forwardStatus').textContent=e.message;}finally{b.disabled=false;await refresh();}
  };
  $('#supplierResolutionForm').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('[type=submit]');button.disabled=true;try{const body={outcome:form.elements.outcome.value,evidence:form.elements.evidence.value,providerChecked:form.elements.providerChecked.checked,externalIds:form.elements.externalIds.value.split(',').map(v=>v.trim()).filter(Boolean)};const result=await api('/api/admin/supplier-orders/'+$('#resolveShipmentId').value+'/resolve',body);$('#integrationStatus').textContent=result.message;$('#supplierResolution').hidden=true;form.reset();await refresh();}catch(e){$('#resolutionStatus').textContent=e.message;}finally{button.disabled=false;}};
  $('#refreshSuppliers').onclick=()=>refresh().catch(e=>{$('#integrationStatus').textContent=e.message;});
  (async()=>{try{await api('/api/admin/metrics');csrf=(await api('/api/auth/csrf')).csrfToken;$('#integrationWorkspace').hidden=false;await refresh();}catch(e){$('#integrationStatus').textContent='Administrator access required. Sign in through the Admin tab to continue.';}})();
})();
