const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const qs=new URLSearchParams(location.search);
const bootstrap=(()=>{try{return JSON.parse(document.getElementById('productBootstrap')?.textContent||'null');}catch{return null;}})();
const productId=bootstrap?.product?.id||qs.get('id');
let products=[],product=null,qty=1,currentView=0,selectedVariant=null;
let currency='USD';
const cart=()=>JSON.parse(localStorage.getItem('nc_cart')||'[]');
const saveCart=x=>localStorage.setItem('nc_cart',JSON.stringify(x));
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency}).format(Number(v)||0);
const stars=r=>{const n=Math.round(Number(r)||0);return '★'.repeat(n)+'☆'.repeat(Math.max(0,5-n))};
const pct=p=>p.oldPrice?Math.max(0,Math.round((1-p.price/p.oldPrice)*100)):0;
function showToast(msg){let t=$('#productToast');if(!t){t=document.createElement('div');t.id='productToast';t.className='product-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>t.classList.remove('show'),1800)}
function addCart(id,quantity=1,variantId=null,source=null){const c=cart();const previous=c.reduce((s,i)=>s+i.qty,0);const key=variantId||id;const row=c.find(x=>(x.variantId||x.id)===key);if(row)row.qty=Math.min(20,row.qty+quantity);else c.push({id,variantId,qty:Math.min(20,Math.max(1,quantity))});saveCart(c);showToast('Added to cart');if(c.reduce((s,i)=>s+i.qty,0)>previous)document.dispatchEvent(new CustomEvent('novacart:cart-added',{detail:{source}}));}
function updateImage(){const imgs=(product.images||[]).map(x=>x.url).filter(Boolean);const fallback=product.image;const source=imgs[currentView]||fallback;$('#mainProductImage').src=source;$('#mainProductImage').alt=product.title;$('#prevImage').disabled=imgs.length<=1;$('#nextImage').disabled=imgs.length<=1;$('#imageCounter').textContent=`${Math.min(currentView+1,Math.max(1,imgs.length))} / ${Math.max(1,imgs.length)}`;$$('.gallery-thumb').forEach((x,i)=>x.classList.toggle('active',i===currentView));for(let i=0;i<4;i++){const el=$('#thumb'+i);if(!el)continue;const u=imgs[i]||fallback;el.src=u;el.closest('button').style.display=i<imgs.length?'':'none';el.closest('button').setAttribute('aria-label','View product image '+(i+1));el.closest('button').setAttribute('aria-pressed',String(i===currentView));}}
async function loadReviews(){try{const r=await fetch(`/api/products/${encodeURIComponent(product.id)}/reviews`);const j=await r.json();const list=j.reviews||[];const html=list.length?list.map(x=>`<article class="review-card"><div class="review-top"><b>${escapeHtml(x.title||'Verified purchase')}</b><span>${stars(x.rating)}</span></div><p>${escapeHtml(x.body||'')}</p><small>${escapeHtml(x.name||'Verified buyer')} · ${new Date(x.createdAt).toLocaleDateString()}</small></article>`).join(''):`<div class="empty-reviews">No approved reviews yet. Verified buyers can leave the first one.</div>`;$('#reviews').innerHTML=html;$('#reviewGrid').innerHTML=html;if(list.length){const avg=list.reduce((s,x)=>s+Number(x.rating||0),0)/list.length;$('#reviewScore').textContent=avg.toFixed(1);$('#reviewCount').textContent=`${list.length} approved reviews`;}}catch{$('#reviews').innerHTML='<div class="empty-reviews">Reviews are temporarily unavailable.</div>';$('#reviewGrid').innerHTML='<div class="empty-reviews">Reviews are temporarily unavailable.</div>';}}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function render(){if(!product){document.body.innerHTML='<main class="not-found"><h1>Product not found</h1><a class="primary-btn" href="/">Back to shop</a></main>';return}
 if(!selectedVariant&&product.variants?.length)selectedVariant=product.variants[0];document.title=bootstrap?.title||product.seoTitle||`${product.title} — NovaCart`; const meta=document.querySelector('meta[name="description"]'); if(meta) meta.content=product.seoDescription||product.description; let ld=document.getElementById('productStructuredData'); if(!ld){ld=document.createElement('script');ld.id='productStructuredData';ld.type='application/ld+json';document.head.appendChild(ld)} ld.textContent=JSON.stringify({"@context":"https://schema.org","@type":"Product",name:product.title,image:(product.images||[]).map(x=>x.url||x),description:product.description,sku:product.sku||undefined,aggregateRating:product.reviews?{"@type":"AggregateRating",ratingValue:Number(product.rating||0),reviewCount:Number(product.reviews||0)}:undefined,offers:{"@type":"Offer",price:Number((selectedVariant?selectedVariant.price:product.price)||0).toFixed(2),priceCurrency:currency,availability:(selectedVariant?selectedVariant.stock:product.stock)>0?"https://schema.org/InStock":"https://schema.org/OutOfStock",url:bootstrap?.canonical||location.href}});
 $('#crumbCat').textContent=product.cat;$('#crumbTitle').textContent=product.title;$('#detailCat').textContent=product.cat.toUpperCase();$('#detailTitle').textContent=product.title;$('#detailBadge').textContent=product.badge||'NOVA PICK';$('#detailRating').textContent=Number(product.reviews)>0?Number(product.rating).toFixed(1):'No reviews yet';$('#detailReviews').textContent=Number(product.reviews)>0?`${Number(product.reviews).toLocaleString()} reviews`:'Be the first';$('#detailStars').textContent=Number(product.reviews)>0?stars(product.rating):'';$('#detailPrice').textContent=money(selectedVariant?selectedVariant.price:product.price);$('#detailDescription').textContent=product.description;$('#reviewScore').textContent=Number(product.reviews)>0?Number(product.rating).toFixed(1):'—';$('#reviewCount').textContent=`${Number(product.reviews||0).toLocaleString()} verified reviews`;
 const old=selectedVariant?.oldPrice??product.oldPrice;if(old){$('#detailOldPrice').textContent=money(old);$('#detailDiscount').textContent=`${pct({...product,price:selectedVariant?selectedVariant.price:product.price,oldPrice:old})}% OFF`;}else{$('#detailOldPrice').textContent='';$('#detailDiscount').textContent='';}
 $('#longCopy').textContent=`${product.description} NovaCart keeps delivery choices, purchase protection and order tracking clear throughout your shopping journey.`;
 const stock=selectedVariant?selectedVariant.stock:product.stock;$('#addToCart').disabled=stock<=0;$('#buyNow').disabled=stock<=0;$('#stockText').textContent=stock>0?'In stock':'Out of stock';$('#stockDetail').textContent=stock>0?`${stock} available · Ready to dispatch`:'Currently unavailable';
 const imgs=(product.images||[]).map(x=>x.url).filter(Boolean);if(!imgs.length)product.images=[{url:product.image}];currentView=Math.min(currentView,Math.max(0,product.images.length-1));updateImage();
 const variants=product.variants||[]; if(selectedVariant && !variants.some(v=>v.id===selectedVariant.id)) selectedVariant=null; if(!selectedVariant&&variants.length) selectedVariant=variants[0]; $('#variantRow').innerHTML=variants.length?variants.map(v=>`<button class="variant-btn ${selectedVariant?.id===v.id?'active':''}" data-variant-id="${escapeHtml(v.id)}">${escapeHtml(v.title)}</button>`).join(''):`<span class="variant-note">Standard selection</span>`;
 $$('.variant-btn').forEach(b=>b.onclick=()=>{selectedVariant=variants.find(v=>v.id===b.dataset.variantId)||null;$$('.variant-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#variantLabel').textContent=selectedVariant?.title||'Standard';render()});$('#variantLabel').textContent=selectedVariant?.title||'Standard';
 $('#specGrid').innerHTML=[['Category',product.cat],['SKU',selectedVariant?.sku||product.sku||'—'],['Availability',`${stock} in stock`],['Customer rating',Number(product.reviews)>0?`${Number(product.rating).toFixed(1)} / 5`:'No reviews yet'],['Reviews',`${Number(product.reviews||0).toLocaleString()} verified reviews`],['Delivery','Options shown at checkout'],['Returns',`${product.returnsDays||30} days where eligible`],['Payment','Secure checkout + COD where available']].map(([k,v])=>`<div><span>${escapeHtml(k)}</span><b>${escapeHtml(v)}</b></div>`).join('');
 const w=JSON.parse(localStorage.getItem('nc_wishlist')||'[]');$('#wishBtn').textContent=w.includes(product.id)?'♥':'♡';$('#wishBtn').setAttribute('aria-pressed',String(w.includes(product.id)));$('#wishBtn').onclick=()=>toggleWish(product.id);
 $('#qtyMinus').onclick=()=>setQty(qty-1);$('#qtyPlus').onclick=()=>setQty(qty+1);$('#addToCart').onclick=()=>addCart(product.id,qty,selectedVariant?.id||null,$('#addToCart'));$('#buyNow').onclick=()=>{addCart(product.id,qty,selectedVariant?.id||null);location.href='/?checkout=1'};$('#editAddress').onclick=()=>location.href='/account.html#addresses';setQty(1);loadReviews();renderRelated();}
function setQty(v){qty=Math.max(1,Math.min(20,v));$('#qtyValue').textContent=qty}
function toggleWish(id){const w=JSON.parse(localStorage.getItem('nc_wishlist')||'[]');const i=w.indexOf(id);if(i>=0)w.splice(i,1);else w.push(id);localStorage.setItem('nc_wishlist',JSON.stringify(w));$('#wishBtn').textContent=w.includes(id)?'♥':'♡';$('#wishBtn').setAttribute('aria-pressed',String(w.includes(id)));showToast(w.includes(id)?'Saved to wishlist':'Removed from wishlist');document.dispatchEvent(new CustomEvent('novacart:wishlist-changed',{detail:{added:w.includes(id),source:$('#wishBtn')}}))}
function renderRelated(){const list=products.filter(x=>x.id!==product.id&&x.cat===product.cat).slice(0,4).concat(products.filter(x=>x.id!==product.id&&x.cat!==product.cat).slice(0,4)).slice(0,4);$('#relatedGrid').innerHTML=list.map(p=>`<a class="related-card" href="/p/${encodeURIComponent(p.slug||p.id)}"><div class="related-img"><img src="${escapeHtml(p.image)}" alt="${escapeHtml(p.title)}"></div><span>${escapeHtml(p.cat)}</span><h3>${escapeHtml(p.title)}</h3><div><strong>${money(p.price)}</strong><small>${Number(p.reviews)>0?`★ ${Number(p.rating).toFixed(1)}`:'No reviews yet'}</small></div></a>`).join('')}
function initTabs(){$$('.detail-tabs button').forEach(b=>b.onclick=()=>{$$('.detail-tabs button').forEach(x=>x.classList.remove('active'));$$('.detail-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');const id=b.dataset.tab;$('#tab-'+id)?.classList.add('active');$$('.detail-tabs button').forEach(x=>x.setAttribute('aria-selected',String(x===b)));if(id==='reviews')document.querySelector('#reviews-section')?.scrollIntoView({behavior:document.documentElement.classList.contains('nc-motion-off')?'instant':'smooth',block:'start'})})}
async function init(){try{
 if(bootstrap){product=bootstrap.product;currency=product.currency;products=bootstrap.related||[];}
 else{const c=await fetch('/api/store-config').then(r=>{if(!r.ok)throw new Error('Store unavailable');return r.json()});currency=c.currency;const r=await fetch(`/api/products/${encodeURIComponent(productId)}`);const j=await r.json();if(!r.ok)throw new Error(j.error||'Not found');product=j.product;}
 $$('[data-needs-js]').forEach(button=>button.disabled=false);render();initTabs();document.body.classList.add('product-ready');
 $$('.gallery-thumb').forEach(b=>b.onclick=()=>{currentView=Number(b.dataset.view);updateImage()});
 $('#prevImage').onclick=()=>{currentView=(currentView+(product.images?.length||1)-1)%(product.images?.length||1);updateImage()};
 $('#nextImage').onclick=()=>{currentView=(currentView+1)%(product.images?.length||1);updateImage()};
 }catch(e){if(bootstrap){showToast('Purchase controls could not load. Refresh this page to retry.');$('#addToCart').disabled=true;$('#buyNow').disabled=true;}else document.body.innerHTML=`<main class="not-found"><h1>Could not load this product.</h1><p>${escapeHtml(e.message)}</p><a class="primary-btn" href="/">Back to shop</a></main>`;}}
init();
