// Seller product controls share the authenticated JSON helper in seller.js.
const catalog={page:1,pages:0,products:[],request:0,editing:null,variantParent:null};
function productImage(url){return /^(https?:\/\/|\/assets\/)/i.test(String(url||''))?url:'/assets/demo-bottle.jpg';}
function notice(id,message){document.getElementById(id).textContent=message;}
async function loadSellerProducts(){
 const token=++catalog.request,form=$('#productFilters');const query=new URLSearchParams(new FormData(form));query.set('page',catalog.page);query.set('limit','12');notice('catalogNotice','Loading products…');
 try{const r=await api('/api/seller/products?'+query);if(!r.r.ok)throw new Error(r.j.error||'Could not load products.');if(token!==catalog.request)return;catalog.products=r.j.products;catalog.pages=r.j.pagination.pages;if(catalog.page>Math.max(1,catalog.pages)){catalog.page=Math.max(1,catalog.pages);return loadSellerProducts();}
  $('#productsList').innerHTML=catalog.products.map(p=>`<article class="seller-product-card" data-product="${esc(p.id)}"><a href="/product.html?id=${encodeURIComponent(p.id)}" class="seller-product-image"><img src="${esc(productImage(p.image))}" alt="${esc(p.title)}" loading="lazy"></a><div class="seller-product-content"><div class="seller-product-meta"><span>${esc(p.cat)}</span><span class="shipment-status">${p.active?'Visible':'Hidden'}</span></div><h3>${esc(p.title)}</h3><p>${esc(payoutMoney(p.price,p.currency))} <small>· ${esc(p.sku||'No SKU')}</small></p><p class="seller-stock-label">Base stock: <strong>${p.stock}</strong> · Variants: ${p.variants.length}</p>${p.supplier_managed?'<small>Stock and variants are managed by supplier sync.</small>':''}<div class="seller-product-actions"><button class="seller-secondary" data-edit-product="${esc(p.id)}" type="button">Edit product</button><button class="seller-secondary" data-stock-product="${esc(p.id)}" type="button" ${p.supplier_managed?'disabled':''}>Update stock</button><button class="seller-secondary" data-variants-product="${esc(p.id)}" type="button" ${p.supplier_managed?'disabled':''}>Variants</button></div><form class="seller-quick-stock" data-stock-form="${esc(p.id)}" hidden><label>Available base stock<input name="stock" type="number" min="0" max="2147483647" step="1" required value="${p.stock}"></label><button class="seller-secondary" type="submit">Save stock</button><button class="seller-secondary" type="button" data-reload-stock>Reload latest</button><p role="status" aria-live="polite"></p></form></div></article>`).join('')||'<div class="seller-empty"><h3>No products found</h3><p>Add your first product or change the search filters.</p></div>';
  $('#productsPage').textContent=`Page ${catalog.pages?catalog.page:0} of ${catalog.pages} · ${r.j.pagination.total} products`;$('#productsPrev').disabled=catalog.page<=1;$('#productsNext').disabled=catalog.page>=catalog.pages;notice('catalogNotice','');
  document.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>openProductEditor(b.dataset.editProduct));
  document.querySelectorAll('[data-variants-product]').forEach(b=>b.onclick=()=>openVariantEditor(b.dataset.variantsProduct));
  document.querySelectorAll('[data-stock-product]').forEach(b=>b.onclick=()=>{const f=b.closest('article').querySelector('[data-stock-form]');f.hidden=!f.hidden;if(!f.hidden)f.elements.stock.focus();});
  document.querySelectorAll('[data-stock-form]').forEach(f=>{
   let current=catalog.products.find(p=>p.id===f.dataset.stockForm);const status=f.querySelector('[role=status]');
   f.querySelector('[data-reload-stock]').onclick=async()=>{try{const r=await api('/api/seller/products/'+encodeURIComponent(current.id));if(!r.r.ok)throw new Error(r.j.error);current=r.j.product;f.elements.stock.value=current.stock;status.textContent='Latest stock loaded.';}catch(e){status.textContent=e.message||'Could not reload.';}};
   f.onsubmit=async event=>{event.preventDefault();const b=f.querySelector('[type=submit]');b.disabled=true;status.textContent='Saving…';try{const r=await api('/api/seller/products/'+encodeURIComponent(current.id),{method:'PATCH',body:JSON.stringify({stock:Number(f.elements.stock.value),expectedStock:current.stock,expectedRevision:current.revision})});if(!r.r.ok)throw new Error(r.j.error||'Could not save stock.');await loadSellerProducts();await refreshSellerOverview();notice('catalogNotice','Stock updated.');}catch(e){status.textContent=e.message;}finally{b.disabled=false;}};
  });
 }catch(e){if(token===catalog.request)notice('catalogNotice',e.message||'Could not load products. Use Refresh to retry.');}
}
function productFields(){return `<label class="span-2">Product title<input name="title" required minlength="2" maxlength="180"></label><label>Category<input name="cat" required maxlength="80" list="sellerCategories"><datalist id="sellerCategories"><option>Tech</option><option>Home</option><option>Lifestyle</option><option>Gadgets</option><option>Beauty</option><option>Other</option></datalist></label><label>SKU<input name="sku" maxlength="80" placeholder="Optional; generated if blank"></label><label>Selling price (${esc(sellerCurrency)})<input name="price" type="number" min="0" step="0.01" max="9999999999.99" required></label><label>Compare-at price (${esc(sellerCurrency)})<input name="oldPrice" type="number" min="0" step="0.01" max="9999999999.99" placeholder="Optional"></label><label>Available base stock<input name="stock" type="number" min="0" step="1" max="2147483647" required><small>Stock still available to sell. Variant stock is managed separately.</small></label><label>Cost price (${esc(sellerCurrency)})<input name="costPrice" type="number" min="0" step="0.01" max="9999999999.99"></label><label>Brand<input name="brand" maxlength="120"></label><label>Badge<input name="badge" maxlength="40" placeholder="NEW"></label><label class="span-2">Main image URL<input name="image" required maxlength="800" placeholder="https://… or /assets/…"><small>Use a direct image URL.</small></label><label class="span-2">Description<textarea name="description" maxlength="3000" rows="4"></textarea></label><label class="span-2">Search keywords<input name="searchKeywords" maxlength="500" placeholder="Separate related words with commas"></label><label class="seller-check span-2"><input name="active" type="checkbox"> Visible in the shop</label>`;}
function catalogDialogs(){
 const holder=document.createElement('div');holder.innerHTML=`<dialog id="productDialog" class="seller-dialog" aria-labelledby="productDialogTitle"><div class="seller-dialog-head"><div><span class="kicker">CATALOGUE EDITOR</span><h2 id="productDialogTitle">Add product</h2></div><button type="button" class="seller-secondary" data-close-dialog="productDialog" aria-label="Close product editor">Close</button></div><form id="productForm" class="seller-editor-form">${productFields()}<p id="productFormNotice" class="span-2" role="status" aria-live="polite"></p><div class="seller-dialog-actions span-2"><button class="seller-secondary" id="reloadProduct" type="button" hidden>Reload latest values</button><button class="seller-secondary" type="button" data-close-dialog="productDialog">Cancel</button><button class="primary-btn" type="submit">Save product</button></div></form></dialog><dialog id="variantDialog" class="seller-dialog" aria-labelledby="variantDialogTitle"><div class="seller-dialog-head"><div><span class="kicker">VARIANT INVENTORY</span><h2 id="variantDialogTitle">Product variants</h2></div><button type="button" class="seller-secondary" data-close-dialog="variantDialog">Close</button></div><p>Each variant has its own price and available stock. Hiding a variant stops new purchases of that option.</p><div id="variantForms"></div><p id="variantNotice" role="status" aria-live="polite"></p></dialog>`;document.body.append(holder);
 document.querySelectorAll('[data-close-dialog]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.closeDialog).close());
 $('#reloadProduct').onclick=()=>openProductEditor(catalog.editing?.id,true);
 $('#productForm').onsubmit=saveProduct;
}
async function openProductEditor(id=null,reload=false){
 try{
  let p=null;if(id){const r=await api('/api/seller/products/'+encodeURIComponent(id));if(!r.r.ok)throw new Error(r.j.error);p=r.j.product;}
  catalog.editing=p;const f=$('#productForm');f.reset();const defaults={title:'',cat:'Other',sku:'',price:'',oldPrice:'',stock:0,costPrice:0,image:'',brand:'',badge:'NEW',description:'',searchKeywords:''};
  for(const k of Object.keys(defaults))f.elements[k].value=p?(p[k]??p[{oldPrice:'old_price',costPrice:'cost_price',searchKeywords:'search_keywords'}[k]]??defaults[k]):defaults[k];f.elements.active.checked=p?.active??true;f.elements.stock.disabled=Boolean(p?.supplier_managed);$('#reloadProduct').hidden=!p;$('#productDialogTitle').textContent=p?'Edit product':'Add product';notice('productFormNotice',reload?'Latest values loaded.':'');
  if(!$('#productDialog').open)$('#productDialog').showModal();f.elements.title.focus();
 }catch(e){notice('catalogNotice',e.message||'Could not open product.');}
}
async function saveProduct(event){
 event.preventDefault();const f=event.target,b=f.querySelector('[type=submit]'),p=catalog.editing;b.disabled=true;notice('productFormNotice','Saving…');
 try{
  const value=Object.fromEntries(new FormData(f));value.active=f.elements.active.checked;for(const k of ['price','stock','costPrice'])if(k in value)value[k]=Number(value[k]);value.oldPrice=value.oldPrice===''?null:Number(value.oldPrice);
  if(p){value.expectedRevision=p.revision;if('stock' in value)value.expectedStock=p.stock;}
  const r=await api('/api/seller/products'+(p?'/'+encodeURIComponent(p.id):''),{method:p?'PATCH':'POST',body:JSON.stringify(value)});if(!r.r.ok)throw new Error(r.j.error||'Could not save product.');$('#productDialog').close();await loadSellerProducts();await refreshSellerOverview();notice('catalogNotice',p?'Product updated.':'Product added.');
 }catch(e){notice('productFormNotice',e.message||'Save failed. Your entered values are still here.');}finally{b.disabled=false;}
}
async function openVariantEditor(id){
 try{const r=await api('/api/seller/products/'+encodeURIComponent(id));if(!r.r.ok)throw new Error(r.j.error);catalog.variantParent=r.j.product;renderVariantForms();if(!$('#variantDialog').open)$('#variantDialog').showModal();}catch(e){notice('catalogNotice',e.message||'Could not load variants.');}
}
function renderVariantForms(){
 const p=catalog.variantParent;$('#variantDialogTitle').textContent=p.title;notice('variantNotice','');
 $('#variantForms').innerHTML=[...p.variants,null].map(v=>`<form class="seller-variant-form" data-variant="${esc(v?.id||'')}"><h3 class="span-2">${v?'Edit variant':'Add a variant'}</h3><label>Option name<input name="title" required minlength="2" maxlength="180" value="${esc(v?.title||'')}" placeholder="e.g. Blue / Large"></label><label>SKU<input name="sku" maxlength="80" value="${esc(v?.sku||'')}" placeholder="Generated if blank"></label><label>Selling price (${esc(sellerCurrency)})<input name="price" type="number" min="0" step="0.01" required value="${v?.price??p.price}"></label><label>Compare-at price (${esc(sellerCurrency)})<input name="oldPrice" type="number" min="0" step="0.01" value="${v?.oldPrice??''}"></label><label>Available stock<input name="stock" type="number" min="0" max="2147483647" step="1" required value="${v?.stock??0}"></label><label>Image URL (optional)<input name="image" maxlength="800" value="${esc(v?.image||'')}"></label><label class="seller-check span-2"><input name="active" type="checkbox" ${v?.active===false?'':'checked'}> Visible option</label><button class="primary-btn" type="submit">${v?'Save variant':'Add variant'}</button><button type="button" class="seller-secondary" data-reload-variants>Reload variants</button><p class="span-2" role="status" aria-live="polite"></p></form>`).join('');
 document.querySelectorAll('[data-reload-variants]').forEach(b=>b.onclick=()=>openVariantEditor(p.id));
 document.querySelectorAll('[data-variant]').forEach(f=>f.onsubmit=async event=>{
  event.preventDefault();const v=p.variants.find(v=>v.id===f.dataset.variant),button=f.querySelector('[type=submit]'),status=f.querySelector('[role=status]');button.disabled=true;status.textContent='Saving…';
  try{const body=Object.fromEntries(new FormData(f));body.active=f.elements.active.checked;body.price=Number(body.price);body.stock=Number(body.stock);body.oldPrice=body.oldPrice===''?null:Number(body.oldPrice);if(v){body.expectedStock=v.stock;body.expectedRevision=v.revision;}
   const r=await api('/api/seller/products/'+encodeURIComponent(p.id)+'/variants'+(v?'/'+encodeURIComponent(v.id):''),{method:v?'PATCH':'POST',body:JSON.stringify(body)});if(!r.r.ok)throw new Error(r.j.error||'Could not save variant.');catalog.variantParent=r.j.product;renderVariantForms();notice('variantNotice',v?'Variant updated.':'Variant added.');await loadSellerProducts();
  }catch(e){status.textContent=e.message;}finally{button.disabled=false;}
 });
}
function setupSellerCatalog(){
 catalogDialogs();$('#createProduct').onclick=()=>openProductEditor();$('#productFilters').onsubmit=e=>{e.preventDefault();catalog.page=1;loadSellerProducts();};$('#refreshProducts').onclick=()=>loadSellerProducts();$('#productsPrev').onclick=()=>{if(catalog.page>1){catalog.page--;loadSellerProducts();}};$('#productsNext').onclick=()=>{if(catalog.page<catalog.pages){catalog.page++;loadSellerProducts();}};
}
