import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {sellerFixture} from './seller-fixture.js';import {json} from './integration-fixture.js';
import {operationsFixture} from './supplier-operations-fixture.js';
test('Amazon tracking sync reaches customer shipment without changing payment or another seller allocation',async()=>{
 const f=await operationsFixture();try{f.state.packages=true;f.state.amazon='Complete';const r=await f.sync();assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.data.fulfillmentStatus,'shipped');assert.equal(r.data.supplierPaymentStatus,'provider_billed');const orders=await f.api('/api/orders',{account:f.accounts.buyer});const o=orders.data.orders.find(o=>o.id===f.row.oid);assert.equal(o.fulfillmentStatus,'partially_shipped');assert.equal(o.payment_status,'paid');assert.equal(o.shipments.find(s=>s.type==='supplier').trackingNumber,'TRACK-ONE');assert.ok(o.shipments.some(s=>s.type==='seller'&&!s.trackingNumber));assert.ok(!JSON.stringify(o.shipments).includes(f.row.reference));}
 finally{await f.close();}
});
test('provider mismatch and outage retain last tracking and use backoff instead of fake status',async()=>{
 const f=await operationsFixture();try{f.state.packages=true;await f.sync();f.state.fail=true;assert.equal((await f.sync()).status,502);let r=await f.read();assert.equal(r.packages[0].trackingNumber,'TRACK-ONE');assert.ok(r.sync_error);assert.ok(new Date(r.next_sync_at)>new Date());f.state.fail=false;f.state.wrong=true;assert.equal((await f.sync()).status,502);assert.equal((await f.read()).packages[0].trackingNumber,'TRACK-ONE');}finally{await f.close();}
});
test('cancellation is explicit, serialized, single-submit and only confirmed by later provider state',async()=>{
 const f=await operationsFixture();try{assert.equal((await f.cancel({})).status,400);const result=await Promise.all([f.cancel(),f.cancel()]);assert.ok(result.every(r=>r.status===200));assert.equal(f.state.cancels,1);assert.equal((await f.read()).cancel_status,'requested');f.state.amazon='Cancelling';await f.sync();assert.notEqual((await f.read()).fulfillment_status,'cancelled');f.state.amazon='Cancelled';await f.sync();assert.equal((await f.read()).cancel_status,'confirmed');assert.equal((await f.read()).fulfillment_status,'cancelled');assert.equal((await f.pool.query('select payment_status from orders where id=$1',[f.row.oid])).rows[0].payment_status,'paid');}finally{await f.close();}
});
test('unknown cancellation never retries automatically and shipped orders block cancellation',async()=>{
 const f=await operationsFixture();try{f.state.cancelFail=true;assert.equal((await f.cancel()).status,502);assert.equal((await f.read()).cancel_status,'unknown');assert.equal((await f.cancel()).data.duplicate,true);assert.equal(f.state.cancels,1);await f.pool.query("update supplier_orders set cancel_status='none',fulfillment_status='shipped' where id=$1",[f.row.id]);assert.equal((await f.cancel()).status,409);}finally{await f.close();}
});
test('AliExpress signed order query distinguishes supplier payment and tracking, without submitting payment',async()=>{
 const f=await operationsFixture({provider:'aliexpress'});try{let r=await f.sync();assert.equal(r.status,200);assert.equal(r.data.supplierPaymentStatus,'awaiting_payment');f.state.ali='WAIT_BUYER_ACCEPT_GOODS';f.state.logistics='SELLER_SEND_GOODS';f.state.packages=true;r=await f.sync();assert.equal(r.data.supplierPaymentStatus,'paid');assert.equal(r.data.packages[0].trackingNumber,'ALI-TRACK');f.state.logistics='BUYER_ACCEPT_GOODS';await f.sync();assert.equal((await f.read()).fulfillment_status,'delivered');assert.equal(f.state.cancels,0);}finally{await f.close();}
});
test('AliExpress cancellation requires provider action and audited confirmation; no false API success',async()=>{
 const f=await operationsFixture({provider:'aliexpress'});try{assert.equal((await f.cancel()).data.cancelStatus,'manual_required');assert.equal(f.state.requests.length,0);const path='/api/admin/supplier-orders/'+f.row.id+'/cancel-review';assert.equal((await f.post(path,{outcome:'confirmed',evidence:'too short'})).status,400);assert.equal((await f.post(path,{outcome:'confirmed',providerChecked:true,evidence:'Provider support confirmed cancellation, reference TEST-123.'})).status,200);assert.equal((await f.read()).cancel_status,'confirmed');assert.equal((await f.pool.query("select count(*)::int n from audit_logs where action='supplier_cancel_manual_review'")).rows[0].n,1);}finally{await f.close();}
});
test('read and cancellation controls enforce administrator access and CSRF',async()=>{
 const f=await operationsFixture();try{const path='/api/admin/supplier-orders/'+f.row.id+'/sync';assert.equal((await f.api(path,{method:'POST',body:{}})).status,401);assert.equal((await f.post(path,{},f.accounts.buyer)).status,403);assert.equal((await f.api(path,{method:'POST',body:{},account:f.admin,csrf:null})).status,403);assert.equal(f.state.requests.length,0);}finally{await f.close();}
});
test('scheduled tracking sync is opt-in, does not pay or forward orders, and honors due times',async()=>{
 const f=await operationsFixture({env:{SUPPLIER_AUTO_SYNC:'true'}});try{let r=await f.application.runSupplierSync();assert.equal(r.orders,1);assert.equal(f.state.reads,1);r=await f.application.runSupplierSync();assert.equal(r.orders,0);assert.equal(f.state.reads,1);assert.ok(f.state.requests.every(r=>r.method==='GET'||r.url==='https://api.amazon.com/auth/o2/token'));}finally{await f.close();}
 const off=await operationsFixture();try{assert.equal((await off.application.runSupplierSync()).enabled,false);assert.equal(off.state.requests.length,0);}finally{await off.close();}
});
test('provider probe does not import; scheduled stock refresh preserves retail price and reports failure',async()=>{
 const f=await operationsFixture({env:{SUPPLIER_AUTO_SYNC:'true'}});try{const selection={externalId:'B012345678',externalSku:'SKU',country:'LK',retailPrice:49,publish:true};const check=await f.post('/api/admin/suppliers/amazon/check',selection);assert.equal(check.status,200);assert.equal(check.data.readVerified,true);assert.equal((await f.pool.query('select count(*)::int n from supplier_products')).rows[0].n,0);
 const imported=await f.post('/api/admin/suppliers/amazon/import',selection);assert.equal(imported.status,201);f.state.stock=4;const result=await f.application.runSupplierSync();assert.equal(result.products,1);let p=(await f.pool.query('select stock,price from products where id=$1',[imported.data.productId])).rows[0];assert.equal(p.stock,4);assert.equal(Number(p.price),49);f.state.fail=true;await f.pool.query('update supplier_products set next_sync_at=now()');await f.application.runSupplierSync();const mapping=(await f.pool.query('select * from supplier_products')).rows[0];assert.ok(mapping.sync_error);assert.ok(new Date(mapping.next_sync_at)>new Date());
 }finally{await f.close();}
});
test('Amazon delivery requires matched package delivery evidence, not just fulfillment completion',async()=>{
 const f=await operationsFixture();try{f.state.amazon='Complete';f.state.packages=true;await f.sync();assert.equal((await f.read()).fulfillment_status,'shipped');f.state.delivery='DELIVERED';f.state.missingPackage=true;await f.sync();assert.equal((await f.read()).fulfillment_status,'shipped');f.state.missingPackage=false;await f.sync();assert.equal((await f.read()).fulfillment_status,'delivered');f.state.delivery='IN_TRANSIT';await f.sync();assert.equal((await f.read()).fulfillment_status,'delivered');}finally{await f.close();}
});
